import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import '../../public/assets/vendor/bootstrap/css/bootstrap.min.css'
import '../../public/assets/vendor/bootstrap-icons/bootstrap-icons.css'
import '../../public/assets/vendor/aos/aos.css'
import '../../public/assets/vendor/glightbox/css/glightbox.min.css'
import '../../public/assets/vendor/swiper/swiper-bundle.min.css'
import '../../public/assets/css/main.css'
import Header from "./components/header";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <Header />
        {children}

        <a href="#" id="scroll-top" className="scroll-top d-flex align-items-center justify-content-center"><i className="bi bi-arrow-up-short"></i></a>

        <Script src="./assets/vendor/bootstrap/js/bootstrap.bundle.min.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/php-email-form/validate.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/aos/aos.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/glightbox/js/glightbox.min.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/purecounter/purecounter_vanilla.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/imagesloaded/imagesloaded.pkgd.min.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/isotope-layout/isotope.pkgd.min.js" strategy="afterInteractive" />
        <Script src="./assets/vendor/swiper/swiper-bundle.min.js" strategy="afterInteractive" />
        <Script src="./assets/js/main.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
